using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;

namespace Wall.Discount.Entity
{
    public class Discount
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        // external Id, easier to reference: 1,2,3 or A, B, C etc.
        public Guid Id { get; set; }
        public string Code { get; set; }
        public int Amount { get; set; }
        public bool AlreadyUsed { get; set; }

    }
}
